version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -lc " python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    env_file:
      - .env
    environment:
      # 容器内用服务名 db 访问 Postgres
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      QDRANT_URL: http://qdrant:6333
      TZ: ${TZ}
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - TZ=${TZ}
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC（可选）
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:6333/readyz || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  pg_data:
  ollama:
  qdrant_data:
